name: Desmond Morris
markdown: redcarpet

exclude:
    - Gemfile
    - Gemfile.lock
    - sass
    - js
    - wercker.yml
    - README.md

assets:
    js_compressor:  uglifier
    css_compressor: sass

disqus:
    shortname: 'desmondmorris'

googleanalytics:
    id: 'UA-8505162-5'

description: Software Engineer and Technology Consultant in NYC.

links:
    github: https://github.com/desmondmorris
    twitter: https://twitter.com/desmondmorris
    linkedin: https://linkedin.com/in/desmondmorris
    avatar: http://dezz.me/pic

vendor:
    jquery: 2.0.3
    normalize: 2.1.3
    modernizr: 2.6.2
