name: Desmond Morris
markdown: redcarpet
pygments: true

exclude:
    - bower.json
    - Gruntfile.js
    - package.json
    - Gemfile
    - Gemfile.lock
    - node_modules
    - wercker.yml

disqus:
    shortname: 'desmondmorris'

googleanalytics:
    id: 'UA-8505162-5'

description: Software engineer. Hip-Hop fan. Runner. Hacker of things. I head up engineering at DoSomething.org

links:
    github: https://github.com/desmondmorris
    twitter: https://twitter.com/desmondmorris
    linkedin: https://linkedin.com/in/desmondmorris
